export const INITIAL_DATA_LOADED = 'LOAD_INITIAL_DATA';
export const INITIAL_DATA_LOADING_FAILED = 'INITIAL_DATA_LOADING_FAILED';
export const INITIAL_DATA_ERROR = 'INITIAL_DATA_ERROR';

export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR';
export const OPEN_SIDEBAR = 'OPEN_SIDEBAR';

export const DELETE_BOOKMARK = 'DELETE_BOOKMARK';
export const DELETE_BOOKMARK_ERROR = 'DELETE_BOOKMARK_ERROR';
export const DELETE_BOOKMARK_SUCCESS = 'DELETE_BOOKMARK_SUCCESS';
export const READD_BOOKMARK_TO_UI = 'READD_BOOKMARK_TO_UI';
export const REMOVE_BOOKMARK_FROM_UI = 'REMOVE_BOOKMARK_FROM_UI';
export const CANCEL_DELETE_BOOKMARK = 'CANCEL_DELETE_BOOKMARK';

export const SHOW_UNDO = 'SHOW_UNDO';
export const HIDE_UNDO = 'HIDE_UNDO';

export const OPEN_BOOKMARK_ADDER = 'OPEN_BOOKMARK_ADDER';
export const CLOSE_BOOKMARK_ADDER = 'CLOSE_BOOKMARK_ADDER';
