export const INITIAL_DATA_LOADED = 'LOAD_INITIAL_DATA';
export const INITIAL_DATA_LOADING_FAILED = 'INITIAL_DATA_LOADING_FAILED';
export const INITIAL_DATA_ERROR = 'INITIAL_DATA_ERROR';

export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR';
export const OPEN_SIDEBAR = 'OPEN_SIDEBAR';
